name: PR Raise Comment

on:
  pull_request:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on PR Raise
        uses: actions/github-script@v6
        with:
          script: |
            const pr = context.payload.pull_request;

            await github.issues.createComment({
              issue_number: pr.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Thanks for raising this PR! We will review it shortly.',
            });
